// GLOBALS - NO WINDOW , WE CAN GET ACCESS TO THEM ANYWHERE IN THE APPLICATION
// __DIRNAME - PATH TO THE DIRECTORY
// __FILENAME - FILE NAME
// REQUIRE - FUNCTION TO USE MODUULE (FILE)
// PROCESS - INFO ABOUT THE ENV ABOUT THE WHERE THE PROGRAM IS BEING EXECUTED

console.log(__dirname)
setInterval(()=>{
console.log("hello world")
},10)

